config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#show'

  resource :skin_simulation
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show; end
end

app/views/home/show.html.erb
<div class="container homepage-container">
  <div class="player">
    <h1>Skin Pattern Simulator</h1>
    <div class="skin-grid-container">
      <canvas id="skin-grid" width="500" height="500"></canvas>
    </div>

    <button onClick="playFrames();" class="play-button">Replay ▶︎</button>
  </div>

  <div class="simulation-form">
    <h2>Create New Simulation</h2>

    <%= form_with url: skin_simulation_path do |form| %>
      <div class="presets">
        <label for="presets">Preset</label>
        <select name="presets">
        </select>
      </div>

      <div class='simulation-buttons'>
        <%= form.submit 'Simulate ❖', class: 'simulate-button' %>
        <%= form.submit 'Reset Options ✖︎', type: 'reset', class: 'reset-button' %>
      </div>

      <div class="advanced-divider">
        <span>
          Advanced
        </span>
      </div>

      <div class="simulation-controls">
        <div class='form-control'>
          <%= form.label :activator_strength %>
          <%= form.range_field :activator_strength,
                              min: -1, max: 1,
                              step: 0.1, value: -0.4 %>
        </div>
    
        <div class='form-control'>
          <%= form.label :inhibitor_strength %>
          <%= form.range_field :inhibitor_strength,
                               min: -1, max: 1,
                               step: 0.1, value: -0.2 %>
        </div>	
    
        <div class='form-control'>
          <%= form.label :striped_direction %>
          <%= form.select :striped_direction, [:none, :vertical, :horizontal] %>
        </div>
      </div>	
    <% end %>
  </div>

  <script>
    runSimulation();
  </script>
</div>